POST http://localhost:8080/api/produtos
content-Type: application/json

{
  "nome": "Coca-Cola 2L",
  "codigoInterno": "COCA001",
  "gtin": "7891234567890",
  "precoVenda": 12.99,
  "ativo": true
}

###

GET http://localhost:8080/api/produtos
accept: application/json

###

GET http://localhost:8080/api/produtos/1
Accept: application/json

###
GET http://localhost:8080/api/produtos/999
accept: application/json

###
GET http://localhost:8080/api/produtos/codigo/COCA001
Accept: application/json

###
GET http://localhost:8080/api/produtos/gtin/7891234567890
Accept: application/json

###
POST http://localhost:8080/api/produtos
Content-Type: application/json

{
  "nome": "Arroz 5hg",
  "codigoInterno": "ARR001",
  "gtin": "7891234567001",
  "precoVenda": 29.90,
  "ativo": true
}

###
PUT http://localhost:8080/api/produtos/1
Content-Type: application/json

{
  "nome": "Coca-Cola 2L",
  "codigoInterno": "COCA001",
  "gtin": "7891234567890",
  "precoVenda": 13.99,
  "ativo": true
}

###

POST http://localhost:8080/api/produtos
Content-Type: application/json

{
  "nome": "",
  "codigoInterno": "TESTe001",
  "gtin": "7890000000001",
  "precoVenda": -10,
  "ativo": true
}

###
POST http://localhost:8080/api/produtos
Content-Type: application/json

{
  "nome": "Feijão 1kg",
  "codigoInterno": "FEI001",
  "gtin": "7891234567801",
  "precoVenda": 12.50,
  "ativo": true
}

###
POST http://localhost:8080/api/produtos
Content-Type: application/json

{
  "nome": "",
  "codigoInterno": "TESTE003",
  "gtin": "7890000000003",
  "precoVenda": -10,
  "ativo": true
}

###
DELETE http://localhost:8080/api/produtos/1

###
GET http://localhost:8080/api/produtos/1
Accept: application/json

###
GET http://localhost:8080/api/produtos

###
GET http://localhost:8080/api/produtos/gtin/7891234567890

###
GET http://localhost:8080/api/produtos/gtin/7891234567801

###
POST http://localhost:8080/api/produtos
Content-Type: application/json

{
  "nome": "Produto com GTIN repetido",
  "codigoInterno": "TESTE999",
  "gtin": "7891234567801",
  "precoVenda": 15.00,
  "ativo": true
}

###
GET http://localhost:8080/api/produtos

###
POST http://localhost:8080/api/produtos
Content-Type: application/json

{
  "nome": "test código interno",
  "codigoInterno": "FEI001",
  "gtin": "78912345678999",
  "precoVenda": 50.00,
  "ativo": true
}

###
PUT http://localhost:8080/api/produtos/2
Content-Type: application/json

{
  "nome": "test aqui",
  "codigoInterno": "tesf001",
  "gtin": "7891234567890",
  "precoVenda": 13.99,
  "ativo": true
}

###
GET http://localhost:8080/api/produtos

###
PUT http://localhost:8080/api/produtos/2
Content-Type: application/json

{
"ativo": true,
"codigoInterno": "ARR001",
"gtin": "7891234567487",
"nome": "Arroz 5kg",
"precoVenda": 28.99
}

###
GET http://localhost:8080/api/produtos/nome/ar

###
GET http://localhost:8080/api/produtos/quantidade

###
PUT http://localhost:8080/api/produtos/1/reativar

###
GET http://localhost:8080/api/produtos

###
GET http://localhost:8080/api/produtos/quantidade

###
PUT http://localhost:8080/api/produtos/2
Content-Type: application/json

{
  "nome": "",
  "codigoInterno": "ARR001",
  "gtin": "7891234567001",
  "precoVenda": -5,
  "ativo": true
}

###
PUT http://localhost:8080/api/produtos/4
Content-Type: application/json

{
  "nome": "Feijão 2Kg",
  "codigoInterno": "FEI001",
  "precoVenda": 13.55
}