POST http://localhost:8080/api/produtos
content-Type: application/json

{
  "nome": "Coca-Cola 2L",
  "codigoInterno": "COCA001",
  "gtin": "7891234567890",
  "precoVenda": 12.99,
  "ativo": true
}

###

GET http://localhost:8080/api/produtos
accept: application/json

###

GET http://localhost:8080/api/produtos/1
Accept: application/json

###
GET http://localhost:8080/api/produtos/999
accept: application/json

###
GET http://localhost:8080/api/produtos/codigo/COCA001
Accept: application/json

###
GET http://localhost:8080/api/produtos/gtin/7891234567890
Accept: application/json

###
POST http://localhost:8080/api/produtos
Content-Type: application/json

{
  "nome": "Arroz 5hg",
  "codigoInterno": "ARR001",
  "gtin": "7891234567001",
  "precoVenda": 29.90,
  "ativo": true
}

###
PUT http://localhost:8080/api/produtos/1
Content-Type: application/json

{
  "nome": "Coca-Cola 2L",
  "codigoInterno": "COCA001",
  "gtin": "7891234567890",
  "precoVenda": 13.99,
  "ativo": true
}

###

POST http://localhost:8080/api/produtos
Content-Type: application/json

{
  "nome": "",
  "codigoInterno": "TESTe001",
  "gtin": "7890000000001",
  "precoVenda": -10,
  "ativo": true
}

###
POST http://localhost:8080/api/produtos
Content-Type: application/json

{
  "nome": "Feijão 1kg",
  "codigoInterno": "FEI001",
  "gtin": "7891234567801",
  "precoVenda": 12.50,
  "ativo": true
}

###
POST http://localhost:8080/api/produtos
Content-Type: application/json

{
  "nome": "",
  "codigoInterno": "TESTE003",
  "gtin": "7890000000003",
  "precoVenda": -10,
  "ativo": true
}

###
DELETE http://localhost:8080/api/produtos/1

###
GET http://localhost:8080/api/produtos/1
Accept: application/json

###
GET http://localhost:8080/api/produtos

###
GET http://localhost:8080/api/produtos/gtin/7891234567890

###
GET http://localhost:8080/api/produtos/gtin/7891234567801

###
POST http://localhost:8080/api/produtos
Content-Type: application/json

{
  "nome": "Produto com GTIN repetido",
  "codigoInterno": "TESTE999",
  "gtin": "7891234567801",
  "precoVenda": 15.00,
  "ativo": true
}

###
GET http://localhost:8080/api/produtos

###
POST http://localhost:8080/api/produtos
Content-Type: application/json

{
  "nome": "test código interno",
  "codigoInterno": "FEI001",
  "gtin": "78912345678999",
  "precoVenda": 50.00,
  "ativo": true
}

###
PUT http://localhost:8080/api/produtos/2
Content-Type: application/json

{
  "nome": "test aqui",
  "codigoInterno": "tesf001",
  "gtin": "7891234567890",
  "precoVenda": 13.99,
  "ativo": true
}

###
GET http://localhost:8080/api/produtos

###
PUT http://localhost:8080/api/produtos/2
Content-Type: application/json

{
"ativo": true,
"codigoInterno": "ARR001",
"gtin": "7891234567487",
"nome": "Arroz 5kg",
"precoVenda": 28.99
}

###
GET http://localhost:8080/api/produtos/nome/ar

###
GET http://localhost:8080/api/produtos/quantidade

###
PUT http://localhost:8080/api/produtos/1/reativar

###
GET http://localhost:8080/api/produtos

###
GET http://localhost:8080/api/produtos/quantidade

###
PUT http://localhost:8080/api/produtos/2
Content-Type: application/json

{
  "nome": "",
  "codigoInterno": "ARR001",
  "gtin": "7891234567001",
  "precoVenda": -5,
  "ativo": true
}

###
PUT http://localhost:8080/api/produtos/4
Content-Type: application/json

{
  "nome": "Feijão 2Kg",
  "codigoInterno": "FEI001",
  "precoVenda": 13.55
}

###
POST http://localhost:8080/api/caixas/abrir
Content-Type: application/json

{
  "saldoInicial": 200.00
}

###
GET http://localhost:8080/api/caixas/aberto

###
PUT http://localhost:8080/api/caixas/fechar

###
GET http://localhost:8080/api/caixas/aberto

###
GET http://localhost:8080/api/caixas/aberto

###
POST http://localhost:8080/api/caixas/abrir
Content-Type: application/json

{
  "saldoInicial": 200.00
}

###
POST http://localhost:8080/api/caixas/movimentacoes/suprimento
Content-Type: application/json

{
  "valor": 100.00,
  "descricao": "Troco adicional"
}

###
POST http://localhost:8080/api/caixas/movimentacoes/sangria
Content-Type: application/json

{
  "valor": 50.00,
  "descricao": "Retirada para o cofre"
}

###
POST http://localhost:8080/api/caixas/movimentacoes/sangria
Content-Type: application/json

{
  "valor": -20.00,
  "descricao": "Teste"
}

###
GET http://localhost:8080/api/caixas/movimentacoes

###
GET http://localhost:8080/api/caixas/aberto

###
GET http://localhost:8080/api/caixas/saldo-esperado

###
POST http://localhost:8080/api/caixas/movimentacoes/suprimento
Content-Type: application/json

{
  "valor": 100.00,
  "descricao": "Troco adicional"
}

###
POST http://localhost:8080/api/caixas/movimentacoes/sangria
Content-Type: application/json

{
  "valor": 50.00,
  "descricao": "Retirada"
}

###
GET http://localhost:8080/api/caixas/aberto

###
POST http://localhost:8080/api/vendas

###
POST http://localhost:8080/api/vendas/1/itens
Content-Type: application/json

{
  "produtoId": 1,
  "quantidade": 2
}

###
GET http://localhost:8080/api/vendas/1

###
POST http://localhost:8080/api/vendas/1/itens
Content-Type: application/json

{
  "produtoId": 4,
  "quantidade": 1
}

###
GET http://localhost:8080/api/vendas/1

###
GET http://localhost:8080/api/vendas/1/itens

###
PUT http://localhost:8080/api/vendas/1/itens/1/quantidade
Content-Type: application/json

{
  "quantidade": 3
}

###
GET http://localhost:8080/api/vendas/1

###
PUT http://localhost:8080/api/vendas/1/itens/1/quantidade
Content-Type: application/json

{
  "quantidade": 0
}

###
DELETE http://localhost:8080/api/vendas/1/itens/2

###
GET http://localhost:8080/api/vendas/1/itens

###
GET http://localhost:8080/api/vendas/1

###
POST http://localhost:8080/api/vendas/1/pagamentos
Content-Type: application/json

{
  "tipo": "PIX",
  "valor": 41.97
}

###
GET http://localhost:8080/api/vendas/1/pagamentos

###
PUT http://localhost:8080/api/vendas/1/finalizar

###
POST http://localhost:8080/api/vendas

###
POST http://localhost:8080/api/vendas/2/itens
Content-Type: application/json

{
  "produtoId": 1,
  "quantidade": 2
}

###
PUT http://localhost:8080/api/vendas/2/finalizar

###
POST http://localhost:8080/api/vendas/2/pagamentos
Content-Type: application/json

{
  "tipo": "PIX",
  "valor": 10.00
}

###
POST http://localhost:8080/api/vendas/2/pagamentos
Content-Type: application/json

{
  "tipo": "DINHEIRO",
  "valor": 17.98
}

###
PUT http://localhost:8080/api/vendas/2/finalizar

###
GET http://localhost:8080/api/vendas/2/pagamentos

###
POST http://localhost:8080/api/vendas/2/pagamentos
Content-Type: application/json

{
  "tipo": "PIX",
  "valor": 5.00
}

###
POST http://localhost:8080/api/vendas/3/pagamentos
Content-Type: application/json

{
  "tipo": "DINHEIRO",
  "valorRecebido": 50.00
}

###
POST http://localhost:8080/api/vendas

###
POST http://localhost:8080/api/vendas/4/itens
Content-Type: application/json

{
  "produtoId": 1,
  "quantidade": 2
}

###
POST http://localhost:8080/api/vendas/4/pagamentos
Content-Type: application/json

{
  "tipo": "DINHEIRO",
  "valorRecebido": 50.00
}

###
PUT http://localhost:8080/api/vendas/4/finalizar

###
GET http://localhost:8080/api/caixas/saldo-esperado

###
GET http://localhost:8080/api/caixas/5/movimentacoes

###
POST http://localhost:8080/api/vendas

###
PUT http://localhost:8080/api/vendas/5/cancelar

###
POST http://localhost:8080/api/vendas/5/itens
Content-Type: application/json

{
  "produtoId": 1,
  "quantidade": 1
}

###
PUT http://localhost:8080/api/vendas/4/cancelar

###
POST http://localhost:8080/api/estoque/produtos/1/entradas
Content-Type: application/json

{
  "quantidade": 20,
  "descricao": "Estoque inicial"
}

###
GET http://localhost:8080/api/estoque/produtos/1/saldo

###
POST http://localhost:8080/api/estoque/produtos/1/saidas
Content-Type: application/json

{
  "quantidade": 3,
  "descricao": "Teste de saída"
}

###
POST http://localhost:8080/api/estoque/produtos/1/saidas
Content-Type: application/json

{
  "quantidade": 18,
  "descricao": "Teste estoque insuficiente"
}

###
POST http://localhost:8080/api/vendas

###
POST http://localhost:8080/api/vendas/6/itens
Content-Type: application/json

{
  "produtoId": 1,
  "quantidade": 2
}

###
GET http://localhost:8080/api/estoque/produtos/1/saldo

###
POST http://localhost:8080/api/vendas/6/pagamentos
Content-Type: application/json

{
  "tipo": "PIX",
  "valorRecebido": 27.98
}

###
PUT http://localhost:8080/api/vendas/6/finalizar

###
GET http://localhost:8080/api/estoque/produtos/1/saldo

###
POST http://localhost:8080/api/vendas

###
POST http://localhost:8080/api/vendas/7/itens
Content-Type: application/json

{
  "produtoId": 1,
  "quantidade": 16
}

###
POST http://localhost:8080/api/vendas/7/pagamentos
Content-Type: application/json

{
  "tipo": "PIX",
  "valorRecebido": 223.84
}

###
PUT http://localhost:8080/api/vendas/7/finalizar

###
GET http://localhost:8080/api/estoque/produtos/1/saldo

###
GET http://localhost:8080/api/estoque/produtos/4/saldo

###
POST http://localhost:8080/api/vendas

###
POST http://localhost:8080/api/vendas/8/itens
Content-Type: application/json

{
  "produtoId": 1,
  "quantidade": 1,
  "produtoId": 4,
  "quantidade": 1
}

###
POST http://localhost:8080/api/vendas/8/pagamentos
Content-Type: application/json

{
  "tipo": "PIX",
  "valorRecebido": 13.55
}

###
PUT http://localhost:8080/api/vendas/8/finalizar

###
GET http://localhost:8080/api/estoque/produtos/1/saldo

###
POST http://localhost:8080/api/estoque/produtos/1/ajustes
Content-Type: application/json

{
  "quantidade": 2,
  "descricao": "Ajuste após contagem física"
}

###
GET http://localhost:8080/api/estoque/produtos/1/saldo

###
POST http://localhost:8080/api/estoque/produtos/1/ajustes
Content-Type: application/json

{
  "quantidade": -2,
  "descricao": "Correção de inventário"
}

###
POST http://localhost:8080/api/estoque/produtos/1/ajustes
Content-Type: application/json

{
  "quantidade": -20,
  "descricao": "Teste de ajuste inválido"
}

###
GET http://localhost:8080/api/estoque/produtos/1/movimentacoes

###
GET http://localhost:8080/api/caixas/saldo-esperado

###
PUT http://localhost:8080/api/caixas/fechar
Content-Type: application/json

{
  "saldoFinal": 340.00
}

###
GET http://localhost:8080/api/caixas/5/extrato

###
GET http://localhost:8080/api/caixas/historico

###
GET /api/caixas/5/extrato

###
GET http://localhost:8080/api/vendas

###
GET http://localhost:8080/api/vendas/6

###
PUT http://localhost:8080/api/vendas/8/cancelar

###
POST http://localhost:8080/api/caixas/abrir
Content-Type: application/json

{
  "saldoInicial": 200.00
}

###
GET http://localhost:8080/api/estoque/produtos/1/saldo

###
POST http://localhost:8080/api/vendas

###
POST http://localhost:8080/api/vendas/9/itens
Content-Type: application/json

{
  "produtoId": 1,
  "quantidade": 2
}

###
POST http://localhost:8080/api/vendas/9/pagamentos
Content-Type: application/json

{
  "tipo": "PIX",
  "valor": 27.98
}

###
PUT http://localhost:8080/api/vendas/9/finalizar

###
GET http://localhost:8080/api/estoque/produtos/1/saldo

###
PUT http://localhost:8080/api/vendas/9/cancelar

###
GET http://localhost:8080/api/estoque/produtos/1/saldo

###
GET http://localhost:8080/api/vendas/6

###
GET http://localhost:8080/api/caixas/6/extrato

###
POST http://localhost:8080/api/vendas
Content-Type: application/json

{
  "caixaId": 6
}

###
POST http://localhost:8080/api/vendas/10/itens
Content-Type: application/json

{
  "produtoId": 1,
  "quantidade": 2
}

###
POST http://localhost:8080/api/vendas/10/pagamentos
Content-Type: application/json

{
  "tipo": "PIX",
  "valor": 27.98
}

###
PUT http://localhost:8080/api/vendas/10/finalizar

###
POST http://localhost:8080/api/estornos/pagamentos/9
Content-Type: application/json

{
  "motivo": "Teste de estorno integral do PDV"
}

###
POST http://localhost:8080/api/estornos/pagamentos/9
Content-Type: application/json

{
  "motivo": "Teste de estorno duplicado"
}

###
PUT http://localhost:8080/api/estornos/1/concluir

###
GET http://localhost:8080/api/caixas/6/extrato