spring.application.name=pdv

# Banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/pdv_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibenate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
